services:
  - type: web
    name: project-sipa
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: PHP_VERSION
        value: 8.2 
      - key: NODE_VERSION
        value: 18.0.0
